---
  - user:
      name: "{{USER}}"
      shell: /bin/bash
      group: admin
   
  - name: "Reset user permission..."
    shell: "chown -R {{USER}}:admin /home/{{USER}}"
    ignore_errors: true

  - name: Set git user.email
    shell: git config --global user.email "john.furr@gmail.com"
    become: yes
    become_user: "{{USER}}"
  
  - name: Set git user.name
    shell: git config --global user.name "John Furr"
    become: yes
    become_user: "{{USER}}"

  - name: Copy .bash_profile
    template: src=bash_profile.j2 dest=/home/ubuntu/.bash_profile owner=ubuntu group=admin mode=0744

  - name: Copy .vimrc file
    template: src=vimrc.j2 dest=/home/ubuntu/.vimrc owner=ubuntu group=admin mode=0744
