---
  - name: Copy gunicorn_start.sh
    template: src=gunicorn_start.sh.j2 dest=/usr/bin/gunicorn_start.sh owner=root group=root mode=0744
   
  - name: Copy gunicorn.service.j2
    template: src=gunicorn.service.j2 dest=/etc/systemd/system/gunicorn.service owner=root group=root
    changed_when: False
    notify:
     - Start Gunicorn

  - name: Start Gunicorn
    service: name=gunicorn state=restarted
