---
- name: deploy ajuma on {{HOST}}
  hosts: "{{HOST}}"
  vars:
    # Defaults can be overridden with --extra-vars flag
    USER: ubuntu
    DB_NAME: ajuma
    DOMAIN: ajumasoftware.com
    NAME: app
    VIRTUALENV: /home/ubuntu/virtualenv
    SOCKFILE: /tmp/gunicorn.sock
    SETTINGS: ajumasoftware.settings
    WSGI: "ajumasoftware.wsgi:application"
    LOGDIR: /home/ubuntu/logs/
    PLATFORM: standalone
    DJANGODIR: "/home/ubuntu/{{NAME}}"
    ACTIVATE: "{{VIRTUALENV}}/bin/activate"
    PYTHON: "{{VIRTUALENV}}/bin/python3"
    REQUIREMENTS: "{{DJANGODIR}}/requirements.txt"
  roles:
    - set_facts
    #- apt_cleanup
    #- system_packages
    #- user

    # Leave these roles in for future reference
    # - hosts_file
    # - role: postgresql
    #  postgresql_version: 9.6
    #  postgresql_users:
    #    - name: ubuntu
    #      pass: 'ajuma'
    #  postgresql_databases:
    #    - name: "{{ DB_NAME }}"
    #      owner: ubuntu
    #  postgresql_user_privileges:
    #    - name: ubuntu
    #      db: "{{ DB_NAME }}"
    #      priv: "ALL"
    #      role_attr_flags: "CREATEDB,CREATEROLE,SUPERUSER"

    - django
    #- gunicorn
    #- nginx
