---
- name: deploy ajuma on {{HOST}}
  hosts: "{{HOST}}"
  vars:
    # Defaults can be overridden with --extra-vars flag
    USER: ubuntu
    REPO: git@github.com:ajumasoftware/main-site.git
    DB_NAME: ajuma
    DOMAIN: ajumasoftware.com
    NAME: app
    VIRTUALENV: "/home/{{USER}}/virtualenv"
    SOCKFILE: /tmp/gunicorn.sock
    SETTINGS: ajumasoftware.settings
    GIT_EMAIL: "john.furr@gmail.com"
    GIT_USER: "John Furr"
    WSGI: "ajumasoftware.wsgi:application"
    LOGDIR: "/home/{{USER}}/logs/"
    PLATFORM: standalone
    DJANGODIR: "/home/{{USER}}/{{NAME}}"
    ACTIVATE: "{{VIRTUALENV}}/bin/activate"
    PYTHON: "{{VIRTUALENV}}/bin/python3"
    REQUIREMENTS: "{{DJANGODIR}}/requirements.txt"
  roles:
    - set_facts
    - apt_cleanup
    - system_packages
    - user

    # Leave these roles in for future reference
    # - hosts_file
    # - role: postgresql
    #  postgresql_version: 9.6
    #  postgresql_users:
    #    - name: ubuntu
    #      pass: 'ajuma'
    #  postgresql_databases:
    #    - name: "{{ DB_NAME }}"
    #      owner: ubuntu
    #  postgresql_user_privileges:
    #    - name: ubuntu
    #      db: "{{ DB_NAME }}"
    #      priv: "ALL"
    #      role_attr_flags: "CREATEDB,CREATEROLE,SUPERUSER"

    - django
    - gunicorn
    - nginx
